export const GET_USER_DATA = "GET_USER_DATA";
export const UPDATE_USER_BIO = "UPDATE_USER_BIO";
export const GET_USER_BIO = "GET_USER_BIO";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";

export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const USERS_LIKES_STATE_CHANGE = "USERS_LIKES_STATE_CHANGE";
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";

export const CLEAR_DATA = "CLEAR_DATA";
